name: Docker Push
description: Tag and push a Docker image to Docker Hub

inputs:
  image_reference:
    description: Docker image reference generated previously (including tag)
    required: true
  username:
    description: Dockerhub username

runs:
  using: composite
  steps:
    - name: Tag Docker image for Docker Hub
      shell: bash
      run: |
        docker tag "${{ inputs.image_reference }}" "${{ inputs.username }}/${{ inputs.image_reference }}"

    - name: Push Docker image to Docker Hub
      shell: bash
      run: |
        docker push "${{ inputs.username }}/${{ inputs.image_reference }}"